##
 # Created by brightSPARK Labs
 # www.brightsparklabs.com
 ##

language: java

jdk:
    - openjdk11

notifications:
    email:
        recipients:
            - ci.travis@brightsparklabs.com
        on_success: change
        on_failure: always

jobs:
  include:
    - stage: unit tests
      script: ./gradlew build
    - stage: publish
      if: branch = master
      script:
      - mkdir -p ~/.gradle
      - echo "gradle.publish.key=${GRADLE_PUBLISH_KEY}" >> ~/.gradle/gradle.properties
      - echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> ~/.gradle/gradle.properties
      - ./gradlew publishPlugins
