##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Gradle Docker CI

on: [ push, pull_request ]

jobs:

  unit-test:
    uses: brightsparklabs/github-actions/.github/workflows/gradle-plugins.yml@master
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  publish:
    uses: brightsparklabs/github-actions/.github/workflows/gradle-plugins.yml@master
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
