##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Gradle Docker CI

on:
  push:
    branches: [ feature, develop, master ]
  pull_request:
    branches: [ feature, develop, master ]

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v2
  #     with:
  #       java-version: '11'
  #       distribution: 'temurin'

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: ./gradlew build

    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'

  publish:
    needs: unit-test
    runs-on: ubuntu-latest

    # - name: Run Unit Tests
    #   run: ./gradlew build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
      - name: Publish Plugins
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          mkdir -p ~/.gradle
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
          ./gradlew publishPlugins

    # - name: Publish
    #   if: github.ref == 'refs/heads/master'
    #   run: |
    #     mkdir -p ~/.gradle
    #     echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
    #     echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
    #     ./gradlew publishPlugins