##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Gradle Docker CI

on: [ push, pull_request ]

jobs:

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Unit Tests
        run: ./gradlew build

  publish:
    needs: unit-test
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish Plugins
        run: |
          mkdir -p ~/.gradle
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
          ./gradlew publishPlugins